### ISSUE TITLE
is there some code review?

### ISSUE THREAD

**Issue by gluck1986** [NodaSoft/hr#58]
there are  interesting test task, but i would like to see some comments in pull requests. I guess that would be fair. For example: 
https://github.com/NodaSoft/hr/pull/56
=) Good luck and success to all!

**Comment by dev-nodasoft** [comment]
Dear [gluck1986](https://github.com/gluck1986),
Thank you for reaching out to us and sharing your code with us. We appreciate your effort and dedication to completing the test task for your job application.
However, we regret to inform you that we are unable to provide a code review at this time. While we understand the importance of receiving feedback on your work, we are not in a position to provide a thorough review due to our current workload and commitments.
We would like to clarify that we usually provide a code review during the first technical interview, where we can discuss your approach and provide feedback on your code.
Thank you for understanding.
Best regards, Nodasoft HR Team.
